name: app

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  repository_dispatch:
    types: [trigger-app-workflow]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run echo
        run: echo "Hello, APP"
