name: app

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for 'terraform/**' changes
        id: check_terraform_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'terraform/'; then
            echo "terraform-changed=true" >> $GITHUB_ENV
          else
            echo "terraform-changed=false" >> $GITHUB_ENV

      - name: Run infra steps if 'terraform/**' changes
        if: env.terraform-changed == 'true'
        run: echo "Running infra steps"

      - name: Run app steps
        run: echo "Running app steps"
