name: app

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  repository_dispatch:
    types: [infra-completed]
  workflow_run:
    workflows: ["infra"]
    types: [completed]
    branches: [main]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run app workflow steps
        run: echo "Executing app workflow"
