name: App2 Workflow

on:
  workflow_run:
    workflows: ["Infra Workflow"]
    types:
      - completed
  workflow_dispatch:


jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine if workflow should run
        id: determine_run_job
        run: |
          # 'workflow_dispatch'イベントでの手動実行時は常に実行
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "run-job=true" >> $GITHUB_ENV
          else
            # Infra Workflowが成功した場合のみファイルの差分をチェック
            if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
              MAIN_BEFORE_LAST_COMMIT=$(git rev-parse origin/main^)
              CURRENT_COMMIT=$(git rev-parse HEAD)

              if git diff --name-only $MAIN_BEFORE_LAST_COMMIT $CURRENT_COMMIT | grep -qE 'infra/'; then
                echo "Changes detected in 'infra/' path."
                echo "run-job=true" >> $GITHUB_ENV
              else
                echo "No changes detected in 'infra/' path."
                echo "run-job=false" >> $GITHUB_ENV
              fi
            else
              echo "Infra Workflow did not succeed."
              echo "run-job=false" >> $GITHUB_ENV
            fi
          fi

      - name: Deploy App
        if: env.run-job == 'true'
        run: |
          echo "Deploying Infra"


      - name: Deploy App
        if: env.run-job == 'true'
        run: |
          echo "Deploying Infra"
