name: App2 Workflow

on:
  workflow_run:
    workflows: ["Infra Workflow"]
    types:
      - completed
  workflow_dispatch:


jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for changes in specific paths
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "workflow_dispatch event triggered."
            echo "run-deploy-step=true" >> $GITHUB_ENV
          else
            # mainブランチの直前のコミットを取得
            MAIN_BEFORE_LAST_COMMIT=$(git rev-parse origin/main^)

            # 現在のワークフローでのHEADコミットを取得
            CURRENT_COMMIT=$(git rev-parse HEAD)

            echo "Main branch before last commit: $MAIN_BEFORE_LAST_COMMIT"
            echo "Current commit: $CURRENT_COMMIT"

            # mainブランチの直前のコミットと現在のコミットの間で変更をチェック
            if git diff --name-only $MAIN_BEFORE_LAST_COMMIT $CURRENT_COMMIT | grep -qE 'infra/'; then
              echo "Changes detected in 'infra/' path."
              echo "run-deploy-step=true" >> $GITHUB_ENV
            else
              echo "No changes detected in 'infra/' path."
              echo "run-deploy-step=false" >> $GITHUB_ENV
            fi
          fi

      - name: Display App
        if: env.run-deploy-step == 'true'
        run: |
          echo "Deploying Infra"

      - name: Display App
        if: env.run-deploy-step == 'true'
        run: |
          echo "Deploying Infra"
