name: Infra Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Infra
      run: |
        echo "Deploying Infra"
        sleep 10