name: Infra Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - 'app/**'
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for changes in 'infra/' path
        id: check_changes_in_infra
        run: |
          # mainブランチの直前のコミットと現在のコミットの間で変更をチェック
          MAIN_BEFORE_LAST_COMMIT=$(git rev-parse origin/main^)
          CURRENT_COMMIT=$(git rev-parse HEAD)

          if git diff --name-only $MAIN_BEFORE_LAST_COMMIT $CURRENT_COMMIT | grep -qE 'infra/'; then
            echo "Changes detected in 'infra/' path."
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "No changes detected in 'infra/' path."
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Deploy App
        if: env.CHANGES_DETECTED == 'true'
        run: |
          echo "Deploying Infra"

      - name: Fail this step
        run: |
          echo "Failing this step intentionally"
          exit 1
