name: infra

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  infra:
    runs-on: ubuntu-latest
    outputs:
      app-changed: ${{ steps.check_app_changes.outputs.app-changed }} # このジョブの出力として、'app/**' パスの変更があったかどうかの結果を設定しています

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 

      - name: Check for 'app/**' changes
        id: check_app_changes
        run: |
          # 'app/**' パスに変更があるかどうかをチェックし、結果を環境変数に設定
          echo "app-changed=$(git diff --name-only HEAD^ HEAD | grep -q 'app/' && echo 'true' || echo 'false')" >> $GITHUB_ENV
          echo "::set-output name=app-changed::$app_changed" # ステップの出力として 'app-changed' を設定

      - name: Run some infra steps
        run: |
          echo "Starting infra steps"
          sleep 30
          echo "Completed infra steps" # インフラ関連のステップが30秒間実行された後に完了

      - name: Dispatch event to trigger app workflow
        if: env.app-changed == 'true' # 'app/**' パスに変更がある場合のみ次のステップを実行
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # GitHub API との認証に使用するトークン
          script: |
            # 'infra-completed' イベントタイプで repository_dispatch イベントを発行
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'infra-completed',
              client_payload: { }
            });
